// pre-compiled from app.jsx — do not edit
/* ============================================================
   Restaurant Decision Report — App entry
   ============================================================ */

const {
  useState: useStateApp
} = React;
function App() {
  // wait for sheet-loader (if present) before first render so live data wins
  const [ready, setReady] = useStateApp(!window.__SHEET_LOADING__);
  React.useEffect(() => {
    if (window.__SHEET_LOADING__) {
      window.__SHEET_LOADING__.finally(() => setReady(true));
    }
  }, []);
  const [area, setArea] = useStateApp(window.AREAS[0]);
  const t = window.useTweaks(window.TWEAK_DEFAULTS);

  // apply tweakable accent color live via CSS var
  React.useEffect(() => {
    document.documentElement.style.setProperty("--accent", t.accent);
    document.documentElement.style.setProperty("--accent-soft", t.accentSoft);
  }, [t.accent, t.accentSoft]);
  if (!ready) {
    return /*#__PURE__*/React.createElement("div", {
      style: {
        display: "grid",
        placeItems: "center",
        height: "100vh",
        color: "var(--ink-3)",
        fontFamily: "var(--font-mono)",
        fontSize: 13
      }
    }, "\u0E01\u0E33\u0E25\u0E31\u0E07\u0E42\u0E2B\u0E25\u0E14\u0E02\u0E49\u0E2D\u0E21\u0E39\u0E25\u0E08\u0E32\u0E01 Google Sheet\u2026");
  }
  const restaurants = window.RESTAURANTS[area.id] || [];
  return /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement(SiteHeader, null), /*#__PURE__*/React.createElement(Hero, {
    area: area,
    onAreaChange: setArea
  }), /*#__PURE__*/React.createElement("div", {
    className: "wrap",
    style: {
      padding: "32px 32px 0"
    }
  }, /*#__PURE__*/React.createElement(AreaBar, {
    area: area,
    onChange: setArea
  })), /*#__PURE__*/React.createElement(ManualRunSection, null), /*#__PURE__*/React.createElement(Ranking, {
    area: area
  }), /*#__PURE__*/React.createElement(Top3, {
    area: area
  }), /*#__PURE__*/React.createElement(Comparison, {
    restaurants: restaurants,
    area: area
  }), /*#__PURE__*/React.createElement(Dataset, {
    area: area
  }), /*#__PURE__*/React.createElement("footer", {
    className: "site-footer"
  }, /*#__PURE__*/React.createElement("div", {
    className: "wrap",
    style: {
      display: "flex",
      justifyContent: "space-between",
      width: "100%"
    }
  }, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
    style: {
      color: "var(--ink-2)",
      fontWeight: 500,
      marginBottom: 4
    }
  }, "\u0E40\u0E22\u0E47\u0E19\u0E19\u0E35\u0E49\u0E01\u0E34\u0E19\u0E2D\u0E30\u0E44\u0E23\u0E14\u0E35?!"), /*#__PURE__*/React.createElement("div", null, "Team Lunch Decision Report \u2014 Generated by automated workflow")), /*#__PURE__*/React.createElement("div", {
    className: "meta"
  }, "v1.0 \xB7 ", area.en, " \xB7 2026-05-26"))), /*#__PURE__*/React.createElement(TweaksUI, {
    t: t,
    setTweak: t.setTweak
  }));
}

/* --------- Tweaks panel --------- */
function TweaksUI({
  t,
  setTweak
}) {
  const {
    TweaksPanel,
    TweakSection,
    TweakColor,
    TweakSelect,
    TweakRadio
  } = window;
  if (!TweaksPanel) return null;
  return /*#__PURE__*/React.createElement(TweaksPanel, {
    title: "Tweaks"
  }, /*#__PURE__*/React.createElement(TweakSection, {
    title: "\u0E2A\u0E35\u0E2B\u0E25\u0E31\u0E01 (accent)"
  }, /*#__PURE__*/React.createElement(TweakColor, {
    label: "Accent",
    value: t.accent,
    onChange: v => {
      // pick a matching soft tint
      const map = {
        "#c0593a": "#f3dcd1",
        "#7a9e7e": "#dde9de",
        "#6b8cae": "#d8e1ea",
        "#a07ba8": "#e5d9e7",
        "#c28b5e": "#eedccb"
      };
      setTweak({
        accent: v,
        accentSoft: map[v] || "#f3dcd1"
      });
    },
    options: ["#c0593a", "#7a9e7e", "#6b8cae", "#a07ba8", "#c28b5e"]
  })));
}
window.TWEAK_DEFAULTS = /*EDITMODE-BEGIN*/{
  "accent": "#c0593a",
  "accentSoft": "#f3dcd1"
} /*EDITMODE-END*/;
ReactDOM.createRoot(document.getElementById("root")).render(/*#__PURE__*/React.createElement(App, null));
